channels:
- conda-forge
dependencies:
- python=3.10.10
- pip<=23.1.2
- pip:
  - mlflow==2.3
  - lz4==4.3.2
  - numpy==1.23.5
  - pandas==1.5.3
  - psutil==5.9.3
  - scikit-learn==1.2.2
  - scipy==1.9.3
  - typing-extensions==4.5.0
  - xgboost==1.7.5
name: mlflow-env
